-- CONNECT AS SYSTEM
BEGIN
   FOR r IN (SELECT username FROM dba_users WHERE username = 'MEDTECH') LOOP
     -- IMPORTANT: Disconnect any active sessions for MEDTECH before dropping
     FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'MEDTECH') LOOP
        EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
     END LOOP;
     -- Give a moment for sessions to terminate
     DBMS_LOCK.SLEEP(2); -- Wait 2 seconds
     EXECUTE IMMEDIATE 'DROP USER MEDTECH CASCADE';
   END LOOP;
EXCEPTION
   WHEN OTHERS THEN
     IF SQLCODE != -01918 THEN -- ORA-01918: user does not exist
         RAISE; -- Re-raise if it's another error
     END IF;
END;
/

-- CONNECT AS SYSTEM
SELECT username FROM dba_users WHERE username = 'MEDTECH';
/


-- CONNECT AS SYSTEM

-- Create the MEDTECH user
CREATE USER MEDTECH IDENTIFIED BY medtech
DEFAULT TABLESPACE "USERS";

-- Grant basic roles and unlimited quota
GRANT "CONNECT" TO MEDTECH ;
ALTER USER MEDTECH QUOTA UNLIMITED ON "USERS";
ALTER USER MEDTECH DEFAULT ROLE "CONNECT";

-- Grant specific system privileges needed by MEDTECH to create and drop objects
GRANT DROP ANY TRIGGER TO MEDTECH ;
GRANT CREATE TRIGGER TO MEDTECH ;
GRANT CREATE ANY PROCEDURE TO MEDTECH ;
GRANT CREATE VIEW TO MEDTECH ;
GRANT CREATE TABLE TO MEDTECH ;
GRANT DROP ANY TABLE TO MEDTECH ;
GRANT CREATE TYPE TO MEDTECH ;
GRANT CREATE TABLESPACE TO MEDTECH ;
GRANT DROP ANY TYPE TO MEDTECH ;
GRANT DROP ANY INDEX TO MEDTECH ;
GRANT CREATE USER TO MEDTECH ;
GRANT DROP ANY VIEW TO MEDTECH ;
GRANT CREATE ANY VIEW TO MEDTECH ;
GRANT CREATE ANY TRIGGER TO MEDTECH ;
GRANT CREATE ANY TABLE TO MEDTECH ;
GRANT CREATE ANY TYPE TO MEDTECH ;
GRANT SELECT ON all_complaints_vw TO PUBLIC;
/

CREATE TABLE USERS (
    username VARCHAR2(50) PRIMARY KEY,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL
);

INSERT INTO USERS VALUES ('admin', 'admin', 'admin');
INSERT INTO USERS VALUES ('customer', 'customer', 'customer');
